/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f3c10f114aee9db81f074b4939173aff)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	DEMO_TOKEN_FRED: "1fc8849b795c1ca6ab2147fa69fce50ac5b42c7d76391e90";
	DEMO_TOKEN_SARA: "5cb358a1f1411c58f0a8eaa10e84386f0f406940519ad2bf";
	PUBLIC_APP_URL: "https://shared-context-web.neutron-m74.workers.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEMO_TOKEN_FRED" | "DEMO_TOKEN_SARA" | "PUBLIC_APP_URL">> {}
}
