import type { ContextObjectView } from "@/domain/types";

const response = (
  displayName: string,
  stance: ContextObjectView["responses"][number]["stance"],
  createdAt: string,
  responseText: string | null = null,
): ContextObjectView["responses"][number] => ({
  displayName,
  stance,
  responseText,
  createdAt,
});

export const mockParticipants = ["Fred", "Sara"];

export const mockSeedObjects: ContextObjectView[] = [
  {
    id: "s9",
    text: "Weekly sync, July 20 — Agreed August release window. Discussed payments dependency. Date not fixed to a specific day.",
    type: "source_document",
    epistemicStatus: "reported_fact",
    lifecycleStatus: "active",
    visibility: "shared",
    origin: "seed",
    authorName: "Fred",
    ownerName: "Fred",
    audienceNames: ["Fred", "Sara"],
    sourceReference: "Weekly sync, July 20",
    supersedesText: null,
    responses: [],
    createdAt: "2026-07-20T09:00:00Z",
  },
  {
    id: "s2",
    text: "The first release ships July 30.",
    type: "decision",
    epistemicStatus: "verified_fact",
    lifecycleStatus: "superseded",
    visibility: "shared",
    origin: "seed",
    authorName: "Sara",
    ownerName: "Sara",
    audienceNames: ["Fred", "Sara"],
    sourceReference: null,
    supersedesText: null,
    responses: [
      response("Fred", "accepted", "2026-07-20T09:05:00Z"),
      response("Sara", "accepted", "2026-07-20T09:05:00Z"),
    ],
    createdAt: "2026-07-20T09:05:00Z",
  },
  {
    id: "s1",
    text: "The first release ships in August.",
    type: "decision",
    epistemicStatus: "verified_fact",
    lifecycleStatus: "active",
    visibility: "shared",
    origin: "seed",
    authorName: "Fred",
    ownerName: "Fred",
    audienceNames: ["Fred", "Sara"],
    sourceReference: "Weekly sync, July 20",
    supersedesText: "The first release ships July 30.",
    responses: [
      response("Fred", "accepted", "2026-07-20T09:30:00Z"),
      response("Sara", "accepted", "2026-07-20T09:30:00Z"),
    ],
    createdAt: "2026-07-20T09:30:00Z",
  },
  {
    id: "s8",
    text: "No paid marketing spend before launch.",
    type: "decision",
    epistemicStatus: "verified_fact",
    lifecycleStatus: "active",
    visibility: "shared",
    origin: "seed",
    authorName: "Fred",
    ownerName: "Fred",
    audienceNames: ["Fred", "Sara"],
    sourceReference: null,
    supersedesText: null,
    responses: [
      response("Fred", "accepted", "2026-07-20T09:45:00Z"),
      response("Sara", "accepted", "2026-07-20T09:45:00Z"),
    ],
    createdAt: "2026-07-20T09:45:00Z",
  },
  {
    id: "s3",
    text: "Sara owns the onboarding flow through launch.",
    type: "task",
    epistemicStatus: "verified_fact",
    lifecycleStatus: "active",
    visibility: "shared",
    origin: "seed",
    authorName: "Sara",
    ownerName: "Sara",
    audienceNames: ["Fred", "Sara"],
    sourceReference: null,
    supersedesText: null,
    responses: [
      response("Fred", "accepted", "2026-07-21T10:00:00Z"),
      response("Sara", "accepted", "2026-07-21T10:00:00Z"),
    ],
    createdAt: "2026-07-21T10:00:00Z",
  },
  {
    id: "s6",
    text: "The payments integration is waiting on vendor approval.",
    type: "blocker",
    epistemicStatus: "reported_fact",
    lifecycleStatus: "active",
    visibility: "shared",
    origin: "seed",
    authorName: "Fred",
    ownerName: "Fred",
    audienceNames: ["Fred", "Sara"],
    sourceReference: null,
    supersedesText: null,
    responses: [
      response("Fred", "accepted", "2026-07-22T11:00:00Z"),
      response("Sara", "accepted", "2026-07-22T11:00:00Z"),
    ],
    createdAt: "2026-07-22T11:00:00Z",
  },
  {
    id: "s7",
    text: "Do we hold the launch if payments isn't live?",
    type: "open_question",
    epistemicStatus: "proposal",
    lifecycleStatus: "active",
    visibility: "shared",
    origin: "seed",
    authorName: "Sara",
    ownerName: "Sara",
    audienceNames: ["Fred", "Sara"],
    sourceReference: null,
    supersedesText: null,
    responses: [],
    createdAt: "2026-07-22T11:10:00Z",
  },
  {
    id: "s4",
    text: "Fred's view: engineering time is the main risk to the launch.",
    type: "perspective",
    epistemicStatus: "perspective",
    lifecycleStatus: "active",
    visibility: "shared",
    origin: "seed",
    authorName: "Fred",
    ownerName: "Fred",
    audienceNames: ["Fred", "Sara"],
    sourceReference: null,
    supersedesText: null,
    responses: [
      response("Fred", "accepted", "2026-07-23T14:00:00Z"),
      response("Sara", "acknowledged", "2026-07-23T14:00:00Z"),
    ],
    createdAt: "2026-07-23T14:00:00Z",
  },
  {
    id: "s5",
    text: "Sara's view: expanding scope is the main risk to the launch.",
    type: "perspective",
    epistemicStatus: "perspective",
    lifecycleStatus: "active",
    visibility: "shared",
    origin: "seed",
    authorName: "Sara",
    ownerName: "Sara",
    audienceNames: ["Fred", "Sara"],
    sourceReference: null,
    supersedesText: null,
    responses: [
      response("Fred", "acknowledged", "2026-07-23T14:20:00Z"),
      response("Sara", "accepted", "2026-07-23T14:20:00Z"),
    ],
    createdAt: "2026-07-23T14:20:00Z",
  },
  {
    id: "s10",
    text: "Fred owns the pricing page copy.",
    type: "task",
    epistemicStatus: "reported_fact",
    lifecycleStatus: "active",
    visibility: "shared",
    origin: "seed",
    authorName: "Fred",
    ownerName: "Fred",
    audienceNames: ["Fred", "Sara"],
    sourceReference: null,
    supersedesText: null,
    responses: [
      response(
        "Sara",
        "disputed",
        "2026-07-24T16:00:00Z",
        "Fred drafts it, but I need to review before it ships.",
      ),
    ],
    createdAt: "2026-07-24T16:00:00Z",
  },
  {
    id: "p1",
    text: "Honestly I don't think we make August at all. If QA takes as long as I expect we're looking at slipping to September, and I don't want to say that out loud until I'm sure.",
    type: "perspective",
    epistemicStatus: "perspective",
    lifecycleStatus: "active",
    visibility: "private",
    origin: "seed",
    authorName: "Fred",
    ownerName: "Fred",
    audienceNames: ["Fred"],
    sourceReference: null,
    supersedesText: null,
    responses: [],
    createdAt: "2026-07-24T18:00:00Z",
  },
  {
    id: "p2",
    text: "Every time we get close to a date Fred adds another must-have. I think the scope is the problem, not the timeline.",
    type: "perspective",
    epistemicStatus: "perspective",
    lifecycleStatus: "active",
    visibility: "private",
    origin: "seed",
    authorName: "Sara",
    ownerName: "Sara",
    audienceNames: ["Sara"],
    sourceReference: null,
    supersedesText: null,
    responses: [],
    createdAt: "2026-07-24T18:30:00Z",
  },
];

const sharedSeedObjects = mockSeedObjects
  .filter((object) => object.visibility === "shared")
  .toSorted((left, right) => right.createdAt.localeCompare(left.createdAt));

const fredPrivateObject = mockSeedObjects.find((object) => object.id === "p1");

if (!fredPrivateObject) {
  throw new Error("Fred's private mock object is missing.");
}

export const mockWorkspaceObjects = {
  fred: [fredPrivateObject, ...sharedSeedObjects].toSorted((left, right) =>
    right.createdAt.localeCompare(left.createdAt),
  ),
  sara: sharedSeedObjects,
};

export const mockPendingProposal: ContextObjectView = {
  id: "pending-launch-date",
  text: "We agreed to launch on August 15.",
  type: "decision",
  epistemicStatus: "proposal",
  lifecycleStatus: "pending",
  visibility: "shared",
  origin: "assistant",
  authorName: "Fred",
  ownerName: "Fred",
  audienceNames: ["Fred", "Sara"],
  sourceReference: null,
  supersedesText: null,
  responses: [],
  createdAt: "2026-07-26T09:58:00Z",
};
